import Topnav from "@/components/topnav/Topnav";
import "./globals.css";
import Bootstrap from "@/components/Bootstartp";
import Navbar from "@/components/navbar/Navbar";
import Footer from "@/components/footer/Footer";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body cz-shortcut-listen="ture">
        <Bootstrap />
        <Topnav />
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
